# Generated by Django 4.0 on 2023-07-26 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0002_initial'),
        ('medias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communaute',
            name='chaine_couverture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communaute_couverture', to='medias.chain'),
        ),
        migrations.AddField(
            model_name='communaute',
            name='chaine_media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communaute_media', to='medias.chain'),
        ),
        migrations.AddField(
            model_name='communaute',
            name='chaine_mise_avant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communaute_mise_avant', to='medias.chain'),
        ),
    ]
