# Generated by Django 4.0 on 2023-07-24 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
        ('together', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.conversation'),
        ),
    ]
