# Generated by Django 4.0 on 2023-07-24 02:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('nb_abonnes', models.IntegerField(default=0)),
                ('objectif', models.CharField(max_length=255)),
                ('activee', models.BooleanField(default=False)),
                ('contacts', models.ManyToManyField(related_name='activites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
