# Generated by Django 4.0 on 2023-07-26 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medias', '0001_initial'),
        ('activity', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='chaine_couverture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites_couverture', to='medias.chain'),
        ),
        migrations.AddField(
            model_name='activite',
            name='chaine_media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites_media', to='medias.chain'),
        ),
        migrations.AddField(
            model_name='activite',
            name='chaine_mise_avant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites_mise_avant', to='medias.chain'),
        ),
        migrations.AddField(
            model_name='activite',
            name='communaute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='community.communaute'),
        ),
        migrations.AddField(
            model_name='activite',
            name='contacts',
            field=models.ManyToManyField(related_name='activites', to=settings.AUTH_USER_MODEL),
        ),
    ]
