# Generated by Django 4.0 on 2023-07-26 06:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('medias', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('code_securite', models.CharField(blank=True, max_length=255, null=True)),
                ('identifiant_unique', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cible', models.CharField(choices=[('amis', 'Amis'), ('communaute', 'Communauté'), ('activites', 'Activités'), ('tout_le_monde', 'Tous le monde')], max_length=50)),
                ('objectif', models.DateField()),
                ('cout_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nombre_cycles', models.IntegerField()),
                ('echeance', models.DateField()),
                ('utilise_fonds_physiques', models.BooleanField(default=False)),
                ('chaine_couverture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_couverture', to='medias.chain')),
                ('chaine_media', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_media', to='medias.chain')),
                ('chaine_mise_avant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_mise_avant', to='medias.chain')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Souscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tranches', models.IntegerField()),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='souscriptions', to='project.projet')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='SourceFinancement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('amis', 'Amis'), ('communaute', 'Communauté'), ('activites', 'Activités'), ('tout_le_monde', 'Tous le monde')], max_length=50)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources_financement', to='project.projet')),
            ],
        ),
        migrations.CreateModel(
            name='Partage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_partage', models.DateTimeField(auto_now_add=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.projet')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.projet')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Investisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taux_retour_investissement', models.DecimalField(decimal_places=2, max_digits=5)),
                ('source_financement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investisseurs', to='project.sourcefinancement')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='GarantieFinancement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tranches', models.IntegerField()),
                ('montant_tranche', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_souscrit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remuneration', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source_financement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garanties', to='project.sourcefinancement')),
            ],
        ),
        migrations.CreateModel(
            name='Financement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=20)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.projet')),
            ],
        ),
        migrations.CreateModel(
            name='Etape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.IntegerField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='project.projet')),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.projet')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='CleinOeilMohhde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.projet')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
