# Generated by Django 4.0 on 2023-10-08 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('project', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='appreciation_projet',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='expert',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expert_qui_suit_projet', to='auth.user'),
        ),
        migrations.AddField(
            model_name='projet',
            name='nombre_vues',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='note_expert',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
