# Generated by Django 4.2.1 on 2023-05-21 13:33

from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
	#('mohhde','add_migration_profile'),
    ]

    operations = [
		#migrations.CreateModel(name="Profile")
    ]
