# Generated by Django 4.0 on 2023-06-14 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mohhde', '0003_initial'),
    ]

    operations = [
    ]
